package org.mdconverter.ambertr.fileparser;

/**
 * Created by miso on 21.01.2016.  <br>
 * Amber specific definitions
 * available sections for an amber input file
 */
public enum AmberSection {

    TITLE,
    POINTERS,
    ATOM_NAME,
    CHARGE,
    ATOMIC_NUMBER,
    MASS,
    ATOM_TYPE_INDEX,
    NUMBER_EXCLUDED_ATOMS,
    NONBONDED_PARM_INDEX,
    RESIDUE_LABEL,
    RESIDUE_POINTER,
    BOND_FORCE_CONSTANT,
    BOND_EQUIL_VALUE,
    ANGLE_FORCE_CONSTANT,
    ANGLE_EQUIL_VALUE,
    DIHEDRAL_FORCE_CONSTANT,
    DIHEDRAL_PERIODICITY,
    DIHEDRAL_PHASE,
    SCEE_SCLAE_FACTOR,
    SCNB_SCLAE_FACTOR,
    SOLTY,
    LENNARD_JONES_ACOEF,
    LENNARD_JONES_BCOEF,
    BONDS_INC_HYDROGEN,
    BONDS_WITHOUT_HYDROGEN,
    ANGLES_INC_HYDROGEN,
    ANGLES_WITHOUT_HYDROGEN,
    DIHEDRALS_INC_HYDROGEN,
    DIHEDRALS_WITHOUT_HYDROGEN,
    EXCLUDED_ATOMS_LIST,
    HBOND_ACOEF,
    HBOND_BCOEF,
    HBCUT,
    AMBER_ATOM_TYPE,
    TREE_CHAIN_CLASSIFICATION,
    JOIN_ARRAY,
    IROTAT,
    SOLVENT_POINTERS,
    ATOMS_PER_MOLECULE,
    BOX_DIMENSIONS,
    CAP_INFO,
    CAP_INFO2,
    RADIUS_SET,
    RADII,
    IPOL,
    POLARIZABILITY,
    SCREEN
}
